### ISSUE TITLE
Comparison

### ISSUE THREAD

**Issue by ShadoW2551** [Destalta/NoBlur#1]
Can you ask for some screenshots to send for comparison ;)?

**Comment by Destalta** [comment]
![Screenshot_7](https://github.com/Destalta/NoBlur/assets/73196418/a8f71f6f-869b-436d-a991-a1aec2969532)
![Screenshot_8](https://github.com/Destalta/NoBlur/assets/73196418/8135c79a-6373-44fd-b1fc-441d53d70779)

![Screenshot_11](https://github.com/Destalta/NoBlur/assets/73196418/884390e2-06d7-4e21-91a9-4dc37f0eb8c2)
![Screenshot_12](https://github.com/Destalta/NoBlur/assets/73196418/5681e2ca-d1e2-472a-9452-69d1e70e5b7c)

**Comment by Destalta** [comment]
![Screenshot_1](https://github.com/Destalta/NoBlur/assets/73196418/bec87350-dfd4-4f77-9e9f-259e4ec54671)
![Screenshot_2](https://github.com/Destalta/NoBlur/assets/73196418/80b19e5c-b651-4fe8-8efe-d90497482bed)

Fog canyon without fog
![Screenshot_3](https://github.com/Destalta/NoBlur/assets/73196418/fe2d0f98-4928-48ad-adad-69c27c964d2b)
![Screenshot_4](https://github.com/Destalta/NoBlur/assets/73196418/06a0eca3-6f79-453a-9b4f-82e90ecc1f77)

![Screenshot_5](https://github.com/Destalta/NoBlur/assets/73196418/702cc685-e31f-4830-90c8-085e2799cc2e)
![Screenshot_6](https://github.com/Destalta/NoBlur/assets/73196418/fbee97b5-c86f-4ef3-8eb9-4dd58d295677)

**Comment by ShadoW2551** [comment]
thx ;O
